#ifndef LFO_CONSTANTS_H
#define LFO_CONSTANTS_H

#include <vector>
#include <cstdint>

constexpr int LFO_SHAPE_SIN = 0;
constexpr int LFO_SHAPE_TRI = 1;
constexpr int LFO_SHAPE_SAW = 2;
constexpr int LFO_SHAPE_SQR = 3;
constexpr int LFO_SHAPE_SAMPLE_AND_HOLD = 4;
const int NUM_LFO_SHAPES = 5;
constexpr uint8_t LFO_SYNC_RATE_4_BARS = 3;
constexpr uint8_t LFO_SYNC_RATE_2_BARS = 7;
constexpr uint8_t LFO_SYNC_RATE_1_BAR = 11;
constexpr uint8_t LFO_SYNC_RATE_DOTTED_HALF = 15;
constexpr uint8_t LFO_SYNC_RATE_HALF = 19;
constexpr uint8_t LFO_SYNC_RATE_HALF_TRIPLET = 23;
constexpr uint8_t LFO_SYNC_RATE_DOTTED_QUARTER = 27;
constexpr uint8_t LFO_SYNC_RATE_QUARTER = 31;
constexpr uint8_t LFO_SYNC_RATE_QUARTER_TRIPLET = 35;
constexpr uint8_t LFO_SYNC_RATE_DOTTED_EIGHTH = 39;
constexpr uint8_t LFO_SYNC_RATE_EIGHTH = 43;
constexpr uint8_t LFO_SYNC_RATE_EIGHTH_TRIPLET = 47;
constexpr uint8_t LFO_SYNC_RATE_DOTTED_SIXTEENTH = 51;
constexpr uint8_t LFO_SYNC_RATE_SIXTEENTH = 55;
constexpr uint8_t LFO_SYNC_RATE_SIXTEENTH_TRIPLET = 59;
constexpr uint8_t LFO_SYNC_RATE_THIRTYSECOND = 63;

const std::vector<uint8_t> LFO_SYNC_RATES = {
    LFO_SYNC_RATE_4_BARS,
    LFO_SYNC_RATE_2_BARS,
    LFO_SYNC_RATE_1_BAR,
    LFO_SYNC_RATE_DOTTED_HALF,
    LFO_SYNC_RATE_HALF,
    LFO_SYNC_RATE_HALF_TRIPLET,
    LFO_SYNC_RATE_DOTTED_QUARTER,
    LFO_SYNC_RATE_QUARTER,
    LFO_SYNC_RATE_QUARTER_TRIPLET,
    LFO_SYNC_RATE_DOTTED_EIGHTH,
    LFO_SYNC_RATE_EIGHTH,
    LFO_SYNC_RATE_EIGHTH_TRIPLET,
    LFO_SYNC_RATE_DOTTED_SIXTEENTH,
    LFO_SYNC_RATE_SIXTEENTH,
    LFO_SYNC_RATE_SIXTEENTH_TRIPLET,
    LFO_SYNC_RATE_THIRTYSECOND
};
const int NUM_LFO_SYNC_RATES = LFO_SYNC_RATES.size();

#endif
