#ifndef SIDECHAIN_CONSTANTS_H
#define SIDECHAIN_CONSTANTS_H

#include <vector>
#include <array>
#include <cstdint>

constexpr int SIDECHAIN_STEPS_PER_BEAT = 4;
constexpr int SIDECHAIN_BEATS_PER_PATTERN = 4;
constexpr int SIDECHAIN_PATTERN_LEAD_STEPS = 1;

constexpr int SIDECHAIN_RHYTHM_STEPS = SIDECHAIN_STEPS_PER_BEAT * SIDECHAIN_BEATS_PER_PATTERN;

constexpr int SIDECHAIN_DEPTH_MIN = 0;
constexpr int SIDECHAIN_DEPTH_MAX = 127;
constexpr int SIDECHAIN_DEFAULT_DEPTH = SIDECHAIN_DEPTH_MAX;

constexpr bool SC_GATE_ON = true;
constexpr bool SC_GATE_OFF = false;

const std::array<bool, SIDECHAIN_RHYTHM_STEPS> SC_PATTERN_QUARTER = {
    SC_GATE_OFF, SC_GATE_OFF, SC_GATE_ON,  SC_GATE_ON,
    SC_GATE_OFF, SC_GATE_OFF, SC_GATE_ON,  SC_GATE_ON,
    SC_GATE_OFF, SC_GATE_OFF, SC_GATE_ON,  SC_GATE_ON,
    SC_GATE_OFF, SC_GATE_OFF, SC_GATE_ON,  SC_GATE_ON
};

const std::array<bool, SIDECHAIN_RHYTHM_STEPS> SC_PATTERN_OFFBEAT_EIGHTH = {
    SC_GATE_OFF, SC_GATE_OFF, SC_GATE_ON,  SC_GATE_OFF, SC_GATE_ON,  SC_GATE_OFF, SC_GATE_ON,  SC_GATE_OFF,
    SC_GATE_ON,  SC_GATE_OFF, SC_GATE_ON,  SC_GATE_OFF, SC_GATE_ON,  SC_GATE_OFF, SC_GATE_ON,  SC_GATE_OFF
};

const std::array<bool, SIDECHAIN_RHYTHM_STEPS> SC_PATTERN_SYNCOPATED = {
    SC_GATE_OFF, SC_GATE_OFF, SC_GATE_ON,  SC_GATE_OFF, SC_GATE_ON,  SC_GATE_OFF, SC_GATE_OFF, SC_GATE_ON,
    SC_GATE_OFF, SC_GATE_OFF, SC_GATE_ON,  SC_GATE_OFF, SC_GATE_ON,  SC_GATE_OFF, SC_GATE_OFF, SC_GATE_ON
};

const std::array<bool, SIDECHAIN_RHYTHM_STEPS> SC_PATTERN_FOUR_FLOOR = {
    SC_GATE_ON,  SC_GATE_OFF, SC_GATE_ON,  SC_GATE_ON,
    SC_GATE_ON,  SC_GATE_OFF, SC_GATE_ON,  SC_GATE_ON,
    SC_GATE_ON,  SC_GATE_OFF, SC_GATE_ON,  SC_GATE_ON,
    SC_GATE_ON,  SC_GATE_OFF, SC_GATE_ON,  SC_GATE_ON
};

constexpr int SC_PATTERN_INDEX_QUARTER = 0;
constexpr int SC_PATTERN_INDEX_OFFBEAT_EIGHTH = 1;
constexpr int SC_PATTERN_INDEX_SYNCOPATED = 2;
constexpr int SC_PATTERN_INDEX_FOUR_FLOOR = 3;

const std::vector<std::array<bool, SIDECHAIN_RHYTHM_STEPS>> SIDECHAIN_PATTERNS = {
    SC_PATTERN_QUARTER,
    SC_PATTERN_OFFBEAT_EIGHTH,
    SC_PATTERN_SYNCOPATED,
    SC_PATTERN_FOUR_FLOOR
};

const int NUM_SIDECHAIN_PATTERNS = SIDECHAIN_PATTERNS.size();

const int SIDECHAIN_DEFAULT_PATTERN_INDEX = SC_PATTERN_INDEX_QUARTER;

constexpr uint8_t gateWetDryForDepth(int depth) {
    if (depth < SIDECHAIN_DEPTH_MIN) depth = SIDECHAIN_DEPTH_MIN;
    if (depth > SIDECHAIN_DEPTH_MAX) depth = SIDECHAIN_DEPTH_MAX;
    return static_cast<uint8_t>(depth);
}

#endif
